version: '3.9'

services:
  node:
    build:
      context: ./files
      dockerfile: Dockerfile
    env_file: dot.env
    working_dir: /app
    ports:
      - ${FROTN_PORT}:3000
    volumes:
      - "./app:/app"
      - ./_roothome/:/root
    depends_on:
      - db
    tty: true
    stdin_open: true


  # db:
  #   image: mariadb:10.5.9

  #   restart: always
  #   ports:
  #     - ${DB_PORT}:3306
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   env_file: dot.env
  #   tty: true
  #   stdin_open: true

volumes:
    db-data:
